### ISSUE TITLE
Use PostgreSQL LISTEN/NOTIFY instead of polling

### ISSUE THREAD

**Issue by joschi** [dataddo/pgq#28]
PostgreSQL supports an asynchronous notification mechanism ([LISTEN](https://www.postgresql.org/docs/16/sql-listen.html), [NOTIFY](https://www.postgresql.org/docs/16/sql-notify.html)) which could be used to listen for updates in a given message queue table.

See https://github.com/joschi/pgq/pull/1 for how the switch to LISTEN/NOTIFY could work.

**Comment by prochac** [comment]
I will use an evasive answer 😅 not now, maybe someday.

For now, it would add complexity we don't have a use case for now.
This project started as a replacement for RabbitMQ

- The first struggle was fixed ack timeout of managed RabbitMQ in AWS, that now should be possible to rise up to 2h.
  https://www.rabbitmq.com/docs/consumers#acknowledgement-timeout
- Second was the amqp lib, reconnect handling, all the async/channel mess etc.
- Third was this bug in wattermill (that solved no.2)
  https://github.com/ThreeDotsLabs/watermill/issues/242

And because we don't do messaging, but job queuing, the Postgres seemed like a fine fit.
Our throughput is small, and the reaction time in seconds is considered quick :smile: 
But our problem is that the jobs can take very long time. I remember one running for 4.5h ... some crazy query on Microsoft SQL :smile:

**Comment by prochac** [comment]
But I will definitely keep an eye on your fork :+1: This is how I honestly thought this lib will serve. It's not a one solution fitting all, but rather something like a starting point.
